using System;
using System.IO;
using System.Linq;
using Xunit;
using Aetherlight.Core;
using Aetherlight.Domain;
using Aetherlight.Save;

namespace Aetherlight.Tests
{
    /// <summary>
    /// Save serialization, including the wire format shared with the
    /// TypeScript implementation. content/reference-save.json is generated by
    /// that side (tools/reference-save.ts) and read by both, so a save written
    /// by one engine loads in the other.
    /// </summary>
    public class SaveTests
    {
        private static string ContentPath(string file) => Path.Combine(AppContext.BaseDirectory, "content", file);

        private static SaveFile Sample()
        {
            var rell = new ActorState
            {
                Id = "rell", DefId = "rell", Level = 8, Xp = 900, Hp = 77, Aether = 19,
            };
            rell.Motes.Add(new MoteInstance("boulder"));
            rell.Motes.Add(new MoteInstance("cinder", MoteState.Standby));
            rell.Equipment[EquipSlot.Weapon] = "iron-blade";
            rell.Statuses.Add(new StatusInstance { StatusId = "scorch", Remaining = 2, SourceId = "foe:x:0" });

            return new SaveFile
            {
                Packs = { "starter" },
                SavedAt = "2026-01-01T00:00:00.000Z",
                PlayTimeSeconds = 120,
                Party = { rell },
                Coin = 500,
                Inventory = { new InventoryEntry { ItemId = "oak-shield", Count = 2 } },
                LooseMotes = { "zephyr" },
                Location = new SaveLocation { MapId = "overworld", X = 10, Y = 4, Facing = "south" },
                Flags = { ["metTheGuide"] = "true" },
            };
        }

        [Fact]
        public void RoundTripsThroughItsOwnWriter()
        {
            var restored = SaveIo.Deserialize(SaveIo.Serialize(Sample()));

            Assert.Equal(SaveIo.CurrentVersion, restored.Version);
            Assert.Equal(500, restored.Coin);
            Assert.Equal("overworld", restored.Location.MapId);
            Assert.Equal(10, restored.Location.X);
            Assert.Single(restored.Party);
            Assert.Equal(8, restored.Party[0].Level);
            Assert.Equal("iron-blade", restored.Party[0].Equipment[EquipSlot.Weapon]);
        }

        [Fact]
        public void PreservesMoteStatesExactly()
        {
            var restored = SaveIo.Deserialize(SaveIo.Serialize(Sample()));
            var motes = restored.Party[0].Motes;
            Assert.Equal(MoteState.Set, motes.Find(m => m.DefId == "boulder")!.State);
            Assert.Equal(MoteState.Standby, motes.Find(m => m.DefId == "cinder")!.State);
        }

        [Fact]
        public void RestoresAnUnlimitedDurationRatherThanZero()
        {
            // JSON has no infinity, so a status that lasts until cured travels
            // as null. If it came back as 0 the status would expire on the next
            // tick; if it came back as a NaN every comparison would silently
            // fail. It has to come back as infinity.
            var save = Sample();
            save.Party[0].Statuses.Add(new StatusInstance { StatusId = "venom", Remaining = double.PositiveInfinity });

            var restored = SaveIo.Deserialize(SaveIo.Serialize(save));
            var venom = restored.Party[0].Statuses.Find(s => s.StatusId == "venom")!;

            Assert.True(double.IsPositiveInfinity(venom.Remaining));
            Assert.True(double.IsPositiveInfinity(venom.Remaining - 1));
        }

        [Fact]
        public void KeepsAFiniteDurationFinite()
        {
            var restored = SaveIo.Deserialize(SaveIo.Serialize(Sample()));
            Assert.Equal(2, restored.Party[0].Statuses.Find(s => s.StatusId == "scorch")!.Remaining);
        }

        [Fact]
        public void RejectsDataThatIsNotASaveFile()
        {
            Assert.Throws<InvalidOperationException>(() => SaveIo.Deserialize("{\"nope\":true}"));
        }

        [Fact]
        public void EscapesStringsThatWouldOtherwiseBreakTheDocument()
        {
            var save = Sample();
            save.Location.MapId = "a \"quoted\" name\nwith a newline and a \\ backslash";
            var restored = SaveIo.Deserialize(SaveIo.Serialize(save));
            Assert.Equal(save.Location.MapId, restored.Location.MapId);
        }

        [Fact]
        public void LoadsTheReferenceSaveWrittenByTheTypeScriptImplementation()
        {
            var save = SaveIo.Deserialize(File.ReadAllText(ContentPath("reference-save.json")));

            Assert.Equal(1450, save.Coin);
            Assert.Equal(7384, save.PlayTimeSeconds);
            Assert.Equal(new[] { "zephyr", "brine" }, save.LooseMotes);
            Assert.Equal("overworld", save.Location.MapId);
            Assert.Equal(12, save.Location.X);
            Assert.Equal(7, save.Location.Y);

            var rell = save.Party.Single();
            Assert.Equal(14, rell.Level);
            Assert.Equal(5200, rell.Xp);
            Assert.Equal("warded-mail", rell.Equipment[EquipSlot.Armor]);

            Assert.Equal(MoteState.Standby, rell.Motes.Find(m => m.DefId == "cinder")!.State);
            var recovering = rell.Motes.Find(m => m.DefId == "loam")!;
            Assert.Equal(MoteState.Recovering, recovering.State);
            Assert.Equal(2, recovering.RecoveryLeft);

            Assert.Equal(2, rell.Statuses.Find(s => s.StatusId == "scorch")!.Remaining);
            // The one written as null by the other implementation.
            Assert.True(double.IsPositiveInfinity(rell.Statuses.Find(s => s.StatusId == "venom")!.Remaining));
        }

        [Fact]
        public void ReSerializingTheReferenceSaveKeepsItLoadable()
        {
            // A save written by this side must survive its own round trip with
            // the same values the other side put in, or the two engines cannot
            // hand saves back and forth.
            var original = SaveIo.Deserialize(File.ReadAllText(ContentPath("reference-save.json")));
            var again = SaveIo.Deserialize(SaveIo.Serialize(original));

            Assert.Equal(original.Coin, again.Coin);
            Assert.Equal(original.Party[0].Level, again.Party[0].Level);
            Assert.Equal(original.Party[0].Motes.Count, again.Party[0].Motes.Count);
            Assert.True(double.IsPositiveInfinity(again.Party[0].Statuses.Find(s => s.StatusId == "venom")!.Remaining));
        }
    }
}
